# Travis-CI Build for RfidResearchGroup/Proxmark3
language: c

#default linux build env is: xenial
compiler: gcc

# move some env variables to homebrew env
env:
  global:
    - HOMEBREW_TRAVIS_BRANCH=$TRAVIS_BRANCH
    - HOMEBREW_TRAVIS_COMMIT=$TRAVIS_COMMIT

# Test on Linux and MacOS
matrix:
  include:
    - os: osx
      osx_image: xcode11
      env: MAKE_PARAMS='PLATFORM_EXTRAS='
    - os: osx
      osx_image: xcode11
      env: MAKE_PARAMS='PLATFORM_EXTRAS=BTADDON'

addons:
  homebrew:
    packages:
      - python3
    update: true

install:
  echo "Installed"

script:
  echo $PATH
  which python3
  
